apiVersion: v1
kind: Service
metadata:
  name: ucloud-nginx
  labels:
    app: ucloud-nginx
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: ucloud-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: ucloud-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: ucloud-nginx
    spec:
      containers:
        - name: nginx
          image: uhub.service.ucloud.cn/ucloud/nginx:1.9.2
          volumeMounts:
            - name: test
              mountPath: /data
          ports:
            - containerPort: 80
      volumes:
        - name: test
          persistentVolumeClaim:
            claimName: test-pvc-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sata-csi-udisk
  resources:
    requests:
      storage: 20Gi
