namePrefix: capu-

commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-ucloud"

bases:
  - crd
  - webhook # Disable this if you're not using the webhook functionality.
  - default
# Enable this when conversion webhooks are implemented
#patchesJson6902:
#- target:
#    group: apiextensions.k8s.io
#    version: v1
#    kind: CustomResourceDefinition
#    name: ucloudclusters.infrastructure.cluster.x-k8s.io
#  path: patch_crd_webhook_namespace.yaml
#- target:
#    group: apiextensions.k8s.io
#    version: v1
#    kind: CustomResourceDefinition
#    name: ucloudmachines.infrastructure.cluster.x-k8s.io
#  path: patch_crd_webhook_namespace.yaml
#- target:
#    group: apiextensions.k8s.io
#    version: v1
#    kind: CustomResourceDefinition
#    name: ucloudmachinetemplates.infrastructure.cluster.x-k8s.io
#  path: patch_crd_webhook_namespace.yaml
